(function(){
'use strict';
/* Электромонтаж дома PRO — большой слой улучшений v1 */
const EXTRA={
 outlet2:['🔌','Двойная розетка',400],water:['💧','Влагозащищённая розетка',200],switch2:['🔘','2-клавишный выключатель',0],pass:['↔️','Проходной выключатель',0],lamp:['💡','Люстра',100],bra:['🔆','Бра',40],internet:['🌐','Интернет RJ45',5],tv:['📺','TV',10],floor:['♨️','Тёплый пол',1200],ac:['❄️','Кондиционер',1500],boiler:['🚿','Бойлер',2000],washer:['🧺','Стиральная машина',2000],dishwasher:['🍽️','Посудомоечная машина',1800],stove:['🔥','Электроплита',7000],oven:['♨️','Духовка',3000]};
Object.keys(EXTRA).forEach(k=>{if(!TYPES[k])TYPES[k]=[EXTRA[k][0],EXTRA[k][1]]});
state.cables=state.cables||[];
if(state.connections&&state.connections.length&&!state.cables.length)state.cables=state.connections.map((c,i)=>({id:'c'+i, name:'Кабель '+(i+1), from:c.a,to:c.b,points:[],type:'ВВГнг-LS',section:2.5,cores:3}));
let hist=[],future=[],routing=null,snapOn=true;
function clone(){return JSON.parse(JSON.stringify(state))}
function remember(){hist.push(clone());if(hist.length>40)hist.shift();future=[]}
function commit(msg){save();status(msg||'Сохранено')}
function undo(){if(!hist.length)return status('Нет изменений для отмены');future.push(clone());state=hist.pop();save();render();status('Отменено')}
function redo(){if(!future.length)return status('Нет действий для повтора');hist.push(clone());state=future.pop();save();render();status('Повторено')}
function obj2(id){return state.objects.find(o=>o.id===id)}
function points(c){let a=obj2(c.from),b=obj2(c.to);return a&&b?[{x:a.x,y:a.y},...(c.points||[]),{x:b.x,y:b.y}]:[]}
function length(c){let p=points(c),n=0;for(let i=1;i<p.length;i++)n+=Math.hypot(p[i].x-p[i-1].x,p[i].y-p[i-1].y);return Math.round(n)}
function cablePath(p){return p.map((q,i)=>(i?'L':'M')+q.x+' '+q.y).join(' ')}
function routePoint(e){let r=canvas.getBoundingClientRect();let x=(e.clientX-r.left)/state.zoom,y=(e.clientY-r.top)/state.zoom;if(snapOn){x=Math.round(x/10)*10;y=Math.round(y/10)*10}return{x:Math.round(x),y:Math.round(y)}}
window.beginProCable=function(){routing={from:null,points:[],cursor:null};state.selected=null;render();status('🔗 Кабель: выберите начальную точку')};
window.cancelProCable=function(){routing=null;render();status('Прокладка отменена')};
function finishCable(id){if(!routing)return;if(routing.from==null){routing.from=id;status('Начало выбрано. Кликайте по плану для поворотов');return}if(routing.from===id)return status('Выберите другую конечную точку');remember();let c={id:'c'+(++state.next),name:'Кабель '+(state.cables.length+1),from:routing.from,to:id,points:routing.points.slice(),type:'ВВГнг-LS',section:2.5,cores:3};state.cables.push(c);state.selected={kind:'proCable',id:c.id};routing=null;commit('Кабель создан');render()}
function drawCables(){document.querySelector('.proCables')?.remove();if(state.tab!=='plan')return;let svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.className='proCables';Object.assign(svg.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:14,overflow:'visible',pointerEvents:'none'});state.cables.forEach(c=>{let p=points(c);if(p.length<2)return;let el=document.createElementNS('http://www.w3.org/2000/svg','path');el.setAttribute('d',cablePath(p));el.style.cssText='fill:none;stroke:'+(state.selected?.kind==='proCable'&&state.selected.id===c.id?'#2563eb':'#ef4444')+';stroke-width:'+(state.selected?.kind==='proCable'&&state.selected.id===c.id?'7':'4')+';stroke-linecap:round;stroke-linejoin:round;pointer-events:stroke;cursor:pointer';el.addEventListener('pointerdown',e=>{e.stopPropagation();state.selected={kind:'proCable',id:c.id};renderProps()});svg.appendChild(el)});if(routing&&routing.from!=null){let p=[{x:obj2(routing.from).x,y:obj2(routing.from).y},...routing.points];if(routing.cursor)p.push(routing.cursor);let el=document.createElementNS('http://www.w3.org/2000/svg','path');el.setAttribute('d',cablePath(p));el.style.cssText='fill:none;stroke:#2563eb;stroke-width:3;stroke-dasharray:8 6;pointer-events:none';svg.appendChild(el)}canvas.prepend(svg)}
function proPlan(){let c=canvas;c.innerHTML='';c.style.transform='scale('+state.zoom+')';c.style.transformOrigin='top left';state.rooms.forEach(r=>{let e=document.createElement('div');e.className='room '+(state.selected?.kind==='room'&&state.selected.id===r.id?'selected':'');e.dataset.id=r.id;e.style.cssText='left:'+r.x+'px;top:'+r.y+'px;width:'+r.w+'px;height:'+r.h+'px';e.innerHTML='<div class="rtitle">'+esc(r.name)+'</div><div class="dims">'+Math.round(r.w)+' × '+Math.round(r.h)+' мм</div>';e.onpointerdown=ev=>{if(routing)return;startDrag(ev,'room',r.id)};e.ondblclick=()=>{let n=prompt('Название комнаты',r.name);if(n){remember();r.name=n;commit();render()}};c.appendChild(e)});state.objects.forEach(o=>{let e=document.createElement('div');e.className='obj '+o.type+' '+(state.selected?.kind==='obj'&&state.selected.id===o.id?'selected':'');e.dataset.id=o.id;e.style.left=o.x+'px';e.style.top=o.y+'px';e.textContent=TYPES[o.type]?.[0]||'⚡';e.title=o.name;e.onpointerdown=ev=>{if(routing){ev.stopPropagation();finishCable(o.id);return}startDrag(ev,'obj',o.id)};e.ondblclick=()=>{let n=prompt('Название',o.name);if(n){remember();o.name=n;commit();render()}};c.appendChild(e)});drawCables()}
function proProps(){let p=document.getElementById('props');if(state.selected?.kind==='proCable'){let c=state.cables.find(x=>x.id===state.selected.id);if(!c)return;p.innerHTML='<div class="card"><h3>🔗 Кабель</h3><div class="field"><label>Название</label><input value="'+esc(c.name)+'" onchange="remember();state.cables.find(x=>x.id===\''+c.id+'\').name=this.value;commit()"></div><div class="field"><label>Тип кабеля</label><select onchange="remember();state.cables.find(x=>x.id===\''+c.id+'\').type=this.value;commit();render()"><option '+(c.type==='ВВГнг-LS'?'selected':'')+'>ВВГнг-LS</option><option '+(c.type==='NYM'?'selected':'')+'>NYM</option><option '+(c.type==='ПВС'?'selected':'')+'>ПВС</option></select></div><div class="field"><label>Сечение, мм²</label><select onchange="remember();state.cables.find(x=>x.id===\''+c.id+'\').section=+this.value;commit();render()"><option '+(c.section==1.5?'selected':'')+'>1.5</option><option '+(c.section==2.5?'selected':'')+'>2.5</option><option '+(c.section==4?'selected':'')+'>4</option><option '+(c.section==6?'selected':'')+'>6</option><option '+(c.section==10?'selected':'')+'>10</option></select></div><div class="field"><label>Жилы</label><input type="number" value="'+c.cores+'" onchange="remember();state.cables.find(x=>x.id===\''+c.id+'\').cores=+this.value;commit()"></div><div class="card"><b>Длина маршрута: '+length(c)+' мм</b><br><span class="muted">С учётом всех поворотов</span></div><button class="danger" onclick="remember();state.cables=state.cables.filter(x=>x.id!==\''+c.id+'\');state.selected=null;commit();render()">🗑 Удалить кабель</button></div>';return}renderPropsOld()}
const renderPropsOld=window.renderProps;
window.renderProps=proProps;
const oldPlan=window.renderPlan;window.renderPlan=proPlan;
const oldRenderObjects=window.renderObjectsOnly;window.renderObjectsOnly=function(){proPlan();proProps()};
const oldSide=window.side;window.side=function(){oldSide();let s=document.getElementById('side');let sec=document.createElement('div');sec.className='sec';sec.textContent='PRO-инструменты';s.appendChild(sec);let b=document.createElement('button');b.className='tool';b.textContent='🔗 Проложить кабель';b.onclick=()=>routing?cancelProCable():beginProCable();s.appendChild(b);let u=document.createElement('button');u.className='tool';u.textContent='↶ Отменить';u.onclick=undo;s.appendChild(u);let r=document.createElement('button');r.className='tool';r.textContent='↷ Повторить';r.onclick=redo;s.appendChild(r);let g=document.createElement('button');g.className='tool';g.textContent='🧲 Привязка к сетке: '+(snapOn?'ВКЛ':'ВЫКЛ');g.onclick=()=>{snapOn=!snapOn;side()};s.appendChild(g);let cat=document.createElement('div');cat.className='sec';cat.textContent='Доп. оборудование';s.appendChild(cat);Object.keys(EXTRA).forEach(k=>{let q=document.createElement('button');q.className='tool';q.textContent=EXTRA[k][0]+' '+EXTRA[k][1];q.onclick=()=>{remember();let id=++state.next;state.objects.push({id,type:k,name:EXTRA[k][1],x:200,y:180,power:EXTRA[k][2],count:1});state.selected={kind:'obj',id};commit('Оборудование добавлено');render()};s.appendChild(q)})};
const oldToolbar=window.toolbar;window.toolbar=function(){oldToolbar();if(state.tab==='plan'){let t=document.getElementById('toolbar');let b=document.createElement('button');b.textContent=routing?'✖ Отменить кабель':'🔗 Кабель';b.className=routing?'danger':'primary';b.onclick=()=>routing?cancelProCable():beginProCable();t.appendChild(b);let z=document.createElement('span');z.className='muted';z.textContent='  Delete — удалить | Esc — отмена | клик — поворот';t.appendChild(z)}};
const oldRender=window.render;window.render=function(){oldRender();if(state.tab==='plan'){setTimeout(()=>{proPlan();proProps()},0)}};
document.addEventListener('pointermove',e=>{if(routing){routing.cursor=routePoint(e);drawCables()}});
document.addEventListener('pointerdown',e=>{if(!routing)return;if(e.target===canvas){let p=routePoint(e);routing.points.push(p);drawCables();status('Поворот добавлен')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&routing){e.preventDefault();cancelProCable()}if((e.key==='Delete'||e.key==='Backspace')&&state.selected?.kind==='proCable'){e.preventDefault();remember();state.cables=state.cables.filter(c=>c.id!==state.selected.id);state.selected=null;commit('Кабель удалён');render()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}});
let oldSave=window.save;window.save=function(){localStorage.setItem(KEY,JSON.stringify(state));status('Сохранено')};
setTimeout(()=>{try{render()}catch(e){console.error(e)}},20);
})();
