import {CABLES,BREAKERS} from './data';
export const num=v=>Number.isFinite(Number(v))?Number(v):0;
export function calculateCurrent(P,U=230,phases=1,cosPhi=.95){return phases===3?P/(Math.sqrt(3)*U*Math.max(cosPhi,.01)):P/U}
export const calculateThreePhaseCurrent=(P,U,cosPhi)=>calculateCurrent(P,U,3,cosPhi);
export const calculateDemandPower=(P,k)=>P*Math.max(0,Math.min(1.5,num(k)||1));
export function calculateCable(I,material='copper'){return CABLES[material].find(c=>c.amp>=I)||CABLES[material][CABLES[material].length-1]}
export function calculateBreaker(I,cableAmp){return BREAKERS.find(b=>b>=I&&b<=cableAmp)||null}
export function calculateVoltageDrop(L,I,size,material='copper',phases=1){const rho=material==='copper'?.0175:.0282; const R=rho*L/Math.max(size,.1); const du=(phases===3?Math.sqrt(3):2)*I*R; return {volts:du,percent:du/230*100}}
export function calculateGroup(group,points,settings){const ps=points.filter(p=>p.groupId===group.id);const total=ps.reduce((s,p)=>s+num(p.power)*num(p.quantity),0);const demand=ps.reduce((s,p)=>s+calculateDemandPower(num(p.power)*num(p.quantity),num(p.demand)),0);const I=calculateCurrent(demand,settings.voltage,settings.phases,settings.cosPhi);const cable=calculateCable(I,settings.cableMaterial);const breaker=calculateBreaker(I,cable.amp);const L=Math.max(...ps.map(p=>num(p.length)),0);const vd=calculateVoltageDrop(L,I,cable.size,settings.cableMaterial,settings.phases,settings.voltage);return {...group,totalPower:total,demandPower:demand,current:I,cable,breaker,length:L,voltageDrop:vd,pointCount:ps.length}}
export function calculatePanel(groups,settings){const maxI=Math.max(0,...groups.map(g=>g.current));const input=calculateBreaker(maxI,125)||125;const modules=1+groups.reduce((s,g)=>s+(g.breaker?1:0)+(g.uzO?2:0),0);return {inputBreaker:input,modules,maxI,totalPower:groups.reduce((s,g)=>s+g.demandPower,0)}}
export function calculateMaterials(project,groups){const map=new Map();const add=(name,qty,unit,price=0)=>{if(qty<=0)return;const old=map.get(name)||{name,quantity:0,unit,price};old.quantity+=qty;map.set(name,old)};project.electricalPoints.forEach(p=>{const e=project._equipment?.find(x=>x.id===p.equipmentId);add(e?.name||p.name,p.quantity,'шт',p.price);if(e?.type==='socket')add('Подрозетник',p.quantity,'шт',400);if(e?.type==='switch')add('Подрозетник',p.quantity,'шт',400);if(e?.type==='junction')add('Распределительная коробка',p.quantity,'шт',1200)});groups.forEach(g=>{if(g.cable)add(`Кабель ${project.cableLabel||'ВВГнг'} 3×${g.cable.size}`,g.length*(1+project.reserve/100),'м',700+g.cable.size*300);if(g.breaker)add(`Автомат ${g.breaker} А`,1,'шт',2500);if(g.uzO)add('УЗО',1,'шт',9000)});add('Щит',1,'шт',25000);return [...map.values()].map(m=>({...m,total:m.quantity*m.price}))}
export function calculateProject(project,equipment){const p={...project,_equipment:equipment};const autoGroups=p.groups.map(g=>calculateGroup(g,p.electricalPoints,p));const groups=autoGroups.length?autoGroups:[];const total=p.electricalPoints.reduce((s,x)=>s+num(x.power)*num(x.quantity),0);const demand=p.electricalPoints.reduce((s,x)=>s+calculateDemandPower(num(x.power)*num(x.quantity),num(x.demand)),0);const current=calculateCurrent(demand,p.voltage,p.phases,p.cosPhi);const cable=calculateCable(current,p.cableMaterial);const panel=calculatePanel(groups,p);const materials=calculateMaterials(p,groups);const cost=materials.reduce((s,m)=>s+m.total,0);return {totalPower:total,demandPower:demand,current,cable,panel,groups,materials,cost,pointCount:p.electricalPoints.length,roomCount:p.rooms.length,cableMeters:groups.reduce((s,g)=>s+g.length*(1+p.reserve/100),0)}}
export function validateProject(project,calc){const warnings=[];if(!project.rooms.length)warnings.push({level:'critical',text:'Нет помещений в проекте.'});if(!project.groups.length&&project.electricalPoints.length)warnings.push({level:'warning',text:'Есть электрические точки, но не созданы группы.'});calc.groups.forEach(g=>{if(!g.pointCount)warnings.push({level:'warning',text:`Группа «${g.name}» пустая.`});if(!g.breaker)warnings.push({level:'critical',text:`Группа «${g.name}»: не найден подходящий автомат.`});const pct=g.voltageDrop.percent;if(pct>project.voltageCritical)warnings.push({level:'critical',text:`Группа «${g.name}»: падение напряжения ${pct.toFixed(1)}%. Увеличьте сечение или уменьшите длину.`});else if(pct>project.voltageWarn)warnings.push({level:'warning',text:`Группа «${g.name}»: падение напряжения ${pct.toFixed(1)}%.`});});return warnings}